version: '3.4'

services:
  server:
    image: ayushaher118/praveen_fleets_server
    build:
      context: .
      dockerfile: Api/Dockerfile
  
  redis:
    image: redis

  webui:
    image: ayushaher118/praveen_fleets_webui:1.2
    ports:
        - "4200:80"
