version: '3.4'

services:
  server:
    image: ayushaher118/praveen_fleets_server
    build:
      context: .
      dockerfile: Dockerfile

  RedisCache:
    image: redis
    ports:
      - 6379:6379

  webui:
    image: ayushaher118/praveen_fleets_webui
    build:
      context: .
      dockerfile: WebUI/Dockerfile
    ports:
      - 8080:80
